src/Entity/CityRisk.php
<?php

namespace App\Entity;

use App\Repository\CityRiskRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRiskRepository::class)
 */
class CityRisk
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="cityRisks")
     * @ORM\JoinColumn(nullable=true)
     */
    private ?City $City;

    /**
     * @ORM\ManyToOne(targetEntity=Risk::class, inversedBy="cityRisks")
     */
    private ?Risk $Risk;

    /**
     * @ORM\ManyToOne(targetEntity=RiskLevel::class, inversedBy="cityRisks")
     */
    private ?RiskLevel $RiskLevel;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?City
    {
        return $this->City;
    }

    public function setCity(?City $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getRisk(): ?Risk
    {
        return $this->Risk;
    }

    public function setRisk(?Risk $Risk): self
    {
        $this->Risk = $Risk;

        return $this;
    }

    public function getRiskLevel(): ?RiskLevel
    {
        return $this->RiskLevel;
    }

    public function setRiskLevel(?RiskLevel $RiskLevel): self
    {
        $this->RiskLevel = $RiskLevel;

        return $this;
    }
}

templates/partials/card_action.html.twig
<div class="card card-outline card-success">
    <div class="card-header">
        <h3 class="card-title">{{ action.title }}</h3>
        <div class="card-tools">
            <span class="badge badge-danger">{{ action.incident.title }}</span>
        </div>
    </div>
    <div class="card-body">
        {{ action.description }}
    </div>
    <div class="card-footer">
        {{ action.pilot.firstName }} - {{ action.pilot.lastName }}
    </div>
</div>

templates/partials/card_incident.html.twig
<div class="card card-danger">
    <div class="card-header">
        <h3 class="card-title">{{ incident.title }}</h3>
        <div class="card-tools">
            <span class="badge badge-dark">{{ incident.category.name }}</span>
            <span class="badge badge-secondary">{{ incident.city.codePostal }} - {{ incident.city.name }}</span>
        </div>
    </div>
    <div class="card-body">
        <h2>{{ incident.title }} - {{ incident.city.name }}</h2>
        <hr>
        {{ incident.description }}
    </div>
    <div class="card-footer text-center">
        <p>Signalé le : {{ incident.date|date('d/m/Y') }} - Par
            : {{ incident.author.firstName }} {{ incident.author.lastName }}</p>
    </div>
</div>

templates/partials/short_card_action.html.twig
<div class="card card-outline card-success short_card">
    <div class="card-header">
        <h3 class="card-title">{{ action.title|u.truncate(25, '...') }}</h3>
    </div>
    <div class="card-body">
        {{ action.description|u.truncate(29, '...') }}
    </div>
    <div class="card-footer">
        {{ action.pilot.firstName }} - {{ action.pilot.lastName }}
    </div>
</div>